id: redis-slave
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: redis-slave
    containers:
      - name: slave
        image: kubernetes/redis
        cpu: 1000
        ports:
          - name: api
            containerPort: 6379
      - name: sentinel
        image: kubernetes/redis
        ports:
          - name: api
            containerPort: 26379
        env:
          - key: SENTINEL
            value: "true"
labels:
  name: redis
  role: slave

    
