#!/bin/bash
#cat /proc/sys/net/ipv4/ip_forward

# clear 
#iptables -t nat -F INPUT
#iptables -t nat -F OUTPUT
#iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to 192.168.1.2:8080
#iptables -t filter -A FORWARD -p tcp -d 192.168.1.2 --dport 8080 -j ACCEPT

# http://opensimulator.org/wiki/Network_Settings
#HOST_IP=192.168.1.194

# robust 8002/tcp
PORT=8002

name=robust
REDIRECT_IP=$(kubecfg list services | grep $name-service | awk '{print $4;}')
REDIRECT_PORT=$(kubecfg list services | grep $name-service | awk '{print $5;}')

iptables -t nat -I PREROUTING -i eth0 -p tcp --dport $PORT -j DNAT --to $REDIRECT_IP:$REDIRECT_PORT
iptables -t filter -I FORWARD -p tcp -d $REDIRECT_IP --dport $PORT -j ACCEPT

# opensim sim_port/tcp
PORT=8801
REDIRECT_IP=192.168.1.201

iptables -t nat -A PREROUTING -i eth0 -p tcp --dport $PORT -j DNAT --to $REDIRECT_IP:$PORT
iptables -t filter -A FORWARD -p tcp -d $REDIRECT_IP --dport $PORT -j ACCEPT

# opensim regions_port/udp
REDIRECT_IP=192.168.1.201

REGION_PORTS=(9000 9001 9002 9003)
for PORT in "${REGION_PORTS[@]}";do
	iptables -t nat -A PREROUTING -i eth0 -p udp --dport $PORT -j DNAT --to $REDIRECT_IP:$PORT
	iptables -t filter -A FORWARD -p udp -d $REDIRECT_IP --dport $PORT -j ACCEPT
done

# restart iptables
#service iptables restart

# list 
iptables -t filter -L FORWARD
iptables -t nat -L PREROUTING
