#!/bin/bash
E_CURRENT_FOLDER=$(pwd)

E_HOST_FOLDER=$E_CURRENT_FOLDER/ke

E_CONTAINER_BIN_FOLDER=/home/opensim80/bin
E_CONTAINER_FOLDER=$E_CONTAINER_BIN_FOLDER/ke
E_CONTAINER_WORKDIR=$E_CONTAINER_BIN_FOLDER/ke

E_HOST_CONFIG_INCLUDE=$E_CURRENT_FOLDER/config-include
E_CONTAINER_CONFIG_INCLUDE=$E_CONTAINER_BIN_FOLDER/config-include

E_SIM_NAME='sim01'
E_SIM_PORT=9001
E_INI_MASTER=$E_CONTAINER_FOLDER/grid/conf/OpenSimDefaults.ini
E_INI_FILE=$E_CONTAINER_FOLDER/grid/conf/OpenSim.ini
E_LOG_CONFIG=$E_CONTAINER_FOLDER/grid/conf/OpenSim.exe.config
E_PID_FILE=$E_CONTAINER_FOLDER/grid/instances/$E_SIM_NAME.pid
E_LOG_FILE=$E_CONTAINER_FOLDER/grid/instances/$E_SIM_NAME.log

E_REGIONLOAD_WEB_URL=http://162.105.17.48/demo.xml

CONTAINER=$E_SIM_NAME
BASE_IMAGE='ubuntu:opensim'
HOST_IP=$(/sbin/ifconfig $ETH0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')

#docker rm $CONTAINER
docker run --rm -i -t -h $CONTAINER --name $CONTAINER -w $E_CONTAINER_WORKDIR -p $HOST_IP:$E_SIM_PORT:$E_SIM_PORT/tcp -v $E_HOST_FOLDER:$E_CONTAINER_FOLDER -v $E_HOST_CONFIG_INCLUDE:$E_CONTAINER_CONFIG_INCLUDE --link mysql:vgeomysql --link robust:vgeorobust -e SIM_NAME=$E_SIM_NAME -e SIM_PORT=$E_SIM_PORT -e INI_MASTER=$E_INI_MASTER -e INI_FILE=$E_INI_FILE -e LOG_CONFIG=$E_LOG_CONFIG -e PID_FILE=$E_PID_FILE -e LOG_FILE=$E_LOG_FILE -e REGIONLOAD_WEB_URL=$E_REGIONLOAD_WEB_URL $BASE_IMAGE 
