FROM ubuntu:vgeo
# copy opensim-preconfigured
ADD ./opensim80 /home/opensim80

# add mapping-volume
#ADD /volumes/opensim_resources/config-include /home/opensim80/bin/config-include
#ADD /volumes/opensim_resources/ke /home/opensim80/bin/ke
#ADD /volumes/opensim_resources/opensim_data /home/opensim80/bin/opensim_data
